### ISSUE TITLE
SpecialAgent causes logging system errors on startup

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#130]
When I add the special agent to a service using -javaagent commandline, I am getting these additional log lines during startup:

```
2019-07-19 19:34:49,22640 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2019-07-19 19:34:49,22645 SLF4J: Defaulting to no-operation (NOP) logger implementation
2019-07-19 19:34:49,22645 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

However, the log appears to be working fine otherwise.

**Comment by randallt** [comment]
I think this is the Wavefront Tracer plugin I wrote causing this actually. The Wavefront OpenTracing SDK seems to cause this (seen with -verbose:class turned on), as it is output during the loading of the Wavefront Tracer.

**Comment by SevaSafris** [comment]
Hi @randallt, these log messages are being produced due to SLF4J's own dynamic service provider loading logic. The SpecialAgent ends up interacting with the SLF4J APIs, yet the provider is not being resolved by the API, or is missing from the runtime completely. It is not SpecialAgent's responsibility to specify the SLF4J provider, so these error messages are unfortunately not within its scope to correct.

**Comment by SevaSafris** [comment]
Hi @randallt, can we close this issue?

**Comment by randallt** [comment]
Yes.
