### ISSUE TITLE
Why is the Oracle JDK required to build?

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#158]
In the readme,

https://github.com/opentracing-contrib/java-specialagent#2121-building

it says that the Oracle JDK is required to build the project, but no further details are given. If building with OpenJDK is required, what would need to be cut from the project?

**Comment by SevaSafris** [comment]
The requirement for Oracle JDK was in part due to complications with [this](http://bytebuddy.net/javadoc/1.9.16/net/bytebuddy/agent/ByteBuddyAgent.html#install--). Additionally, the SpecialAgent uses a few "sun.*" system properties, which are only guaranteed to be present in the Oracle JRE. We have an open issue to resolve coupling.

**Comment by safris** [comment]
SpecialAgent now explicitly supports OpenJDK for development.
