### ISSUE TITLE
After the successful Dynamic Attach, how to shutdown this agent?

### ISSUE THREAD

**Issue by code98** [opentracing-contrib/java-specialagent#214]
After the successful Dynamic Attach, how to shutdown this agent?

I want to remove trace monitoring.

thanks

**Comment by SevaSafris** [comment]
Hi @code98, it is not possible to disable the agent once it has instrumented the runtime. The bytecode manipulations performed by the agent persist for the remaining runtime duration of the target VM.

**Comment by code98** [comment]
Is there any way to disable it?

**Comment by code98** [comment]
The arthas project uses the reset command to clear the bytecode. Can the special agent develop this command?

https://github.com/alibaba/arthas

**Comment by SevaSafris** [comment]
There is no way to undo the [redefinition](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/Instrumentation.html#redefineClasses(java.lang.instrument.ClassDefinition...)) or [retransformation](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/Instrumentation.html#redefineClasses(java.lang.instrument.ClassDefinition...)) operations once they have completed. There is no mechanism to save the revert back to previously unmodified bytecode.

**Comment by SevaSafris** [comment]
The SpecialAgent can, however, support the functionality to "logically"  disable its plugins. This would effectively leave the bytecode as-is (i.e. redefined and retransformed), but would command all plugins to return immediately once invoked. This functionality would not be 100% equivalent to "rolling back" the bytecode to the previously un-redefined and un-retransformed state, but it would resemble this state logically.

**Comment by code98** [comment]
Ok, thank you!
We want to develop a control program, dynamically update the SpecialAgent version, stop the old version of attach, restart a new SpecialAgent, and then attach

**Comment by SevaSafris** [comment]
Thought I have a very limited understanding of the scope of your control program, I don't believe it would be possible to achieve such functionality of "unloading" and "reloading" SpecialAgent. If the SpecialAgent is attached to JVM which SpecialAgent has already attached before, it will simply redo the same redefinition and retransformation modifications as the first time. You can try this yourself. Simply attach SpecialAgent to a running process twice. I know for certain, however, that this will absolutely destabilize the runtime, because of the intricate modifications that SpecialAgent does to the class loading mechanism in the JVM.

**Comment by code98** [comment]
OK, thank you very much for your help.
