### ISSUE TITLE
Not able to get the full trace for our application.

### ISSUE THREAD

**Issue by sattishv** [opentracing-contrib/java-specialagent#254]
Hi team,

We were able to attach the special agent to our JVM and traces are recorded. But the traces aren't complete we couldn't see the full trace.Not sure are we missing any configuration.
Have attached the screenshot and logs for review

Thanks
Sattish.
[wrapper.log](https://github.com/opentracing-contrib/java-specialagent/files/3885786/wrapper.log)
[wrapper.1.log](https://github.com/opentracing-contrib/java-specialagent/files/3885860/wrapper.1.log)

**Comment by SevaSafris** [comment]
Hi @sattishv,

I am not clear on what your issue is. I do not know the context of your application, and also do not know what "traces" you are expecting. The paragraph titled [What is SpecialAgent](https://github.com/opentracing-contrib/java-specialagent/#what-is-specialagent) says:
> the SpecialAgent is itself nothing more than an engine that abstracts the functionality for automatic installation of Instrumentation Plugins, and then connecting them to Tracer Plugins.

You "not seeing traces" is outside the scope of SpecialAgent. If you are "not seeing traces" for a specific 3rd-party library that is in your application, and for which SpecialAgent has an [Instrumentation Plugin](https://github.com/opentracing-contrib/java-specialagent/#61-instrumentation-plugins), then please specify the problem with regard to the scope of the specific plugin.

**Comment by sattishv** [comment]
Hi Safris,

Our service calls 6 downstream services out of 6 services 2 are accessed asynchronous . In the trace captured we dont see the time spent in getting the response from downstream services. I could see only one trace and moreover we didnt see which method took most of the total response time.Do we need configure the agent to capture the calls spanning downstream services.

Sattish.
