### ISSUE TITLE
Possible race condition in "servlet" rule

### ISSUE THREAD

**Issue by prydin** [opentracing-contrib/java-specialagent#316]
I was browsing your code to better understand how to do something similar in another project when I came across what I believe to be a race condition.

https://github.com/opentracing-contrib/java-specialagent/blob/d1fc96b682060d871ad6e5a8cff9440b7aabb884/rule/servlet/src/main/java/io/opentracing/contrib/specialagent/rule/servlet/ServletFilterAgentIntercept.java#L40

The ```ServerFilterAgentIntercept:: servletContextToFilter``` HashMap seems to be read without synchronization. There is synchronization when writing a few lines down, but keep in mind that since the read isn't synchronized, it is possible to get inconsistent results and even crashes due to ```NullPointerExceptions``` etc. There's also a subclass that calls ```remove``` on this Map without synchronizing. 

I suggest you add the proper synchronization and/or make it a ```ConcurrentHashMap```, as well as making it private to ```ServiceFilterAgentIntercept``` to better control access.

**Comment by safris** [comment]
Hi @prydin, thank you for bringing this issue to our attention. You are right to say that `servletContextToFilter` should be a `ConcurrentHashMap`. This would fix the volatility issue -- the `ConcurrentHashMap` ensures that all threads see a consistent value for the variable.

Regarding synchronization:
1. The line you reference in your issue is the start of a [double-check pattern](https://github.com/opentracing-contrib/java-specialagent/blob/d1fc96b682060d871ad6e5a8cff9440b7aabb884/rule/servlet/src/main/java/io/opentracing/contrib/specialagent/rule/servlet/ServletFilterAgentIntercept.java#L40-L47). This pattern avoids from having to synchronize all calls, which improves performance.
1. The [remove call you are referring to](https://github.com/opentracing-contrib/java-specialagent/blob/d1fc96b682060d871ad6e5a8cff9440b7aabb884/rule/servlet/src/main/java/io/opentracing/contrib/specialagent/rule/servlet/JettyAgentIntercept.java#L63) does not need to be synchronized. The context of the `remove` call is for exceptions that occur during the `addFilter` phase, which is itself synchronized.

Thank you for this issue!

**Comment by prydin** [comment]
Thanks for the explanation! 

Just one more remark: I don't think double checking is safe for a ```HashMap```. Keep in mind that a write to a ```HashMap``` can cause the underlying array to grow, in which case the whole map is rebuilt and rearranged. Issuing a ```get``` while that is happening can cause very strange behavior.

Ask me how I know! :)

**Comment by safris** [comment]
Wow, that's interesting. I did not know this. Do you have a link that sheds some more light on this?

**Comment by prydin** [comment]
Here's a link for example:
https://stackoverflow.com/questions/33350489/double-checked-locking-with-regular-hashmap

If you look at the code for HashMap, you'll see that a put does a lot of unprotected accesses to internal structures that are in no way atomic. If one thread is in the opportunistic non-synched code while another thread is in the synched code trying to add a new value, the first thread will be trying to read the internal structures while the second thread is manipulating them. In fact, the default implementation of ```HashMap``` isn't - strictly speaking - threadsafe even for concurrent gets. There's some access counter that's updated even on gets
