### ISSUE TITLE
Utils support for span, object map

### ISSUE THREAD

**Issue by jam01** [opentracing-contrib/java-specialagent#323]
The old java-agent offered a simple weak hash map of objects and spans. See here https://github.com/opentracing-contrib/java-agent/blob/master/opentracing-agent/src/main/java/io/opentracing/contrib/agent/OpenTracingHelper.java#L124

Is this something that maybe we can support as part of the rule utils class or would you recommend a diff approach?

My use case is I have to associate an object with a span in one rule for class A and retrieve that association in a rule for class B.

**Comment by safris** [comment]
Hi @jam01, this utility is deliberately omitted from the SpecialAgent, because rules should not interact with each other. If rules are allowed to be coupled to each other, then what would happen if a user chooses to turn off Rule A when Rule B relies on it? Allowing rule interdependencies would open a pandora's box of complexity that is easier avoided than confronted. What is the specific use-case for which you desire state to be communicated between 2 rules? Let's look at it directly and find another solution.

**Comment by jam01** [comment]
Sure. So in my use case there's heavy use of reactive streams, but in a way that's can't be supported by the reactive context approach; there are two streams and they're not connected, also one is cold and the other hot. Basically I need to associate the object as it leaves the first one with a span and retrieve it when it goes through the second so it can be activated in every reactive processor.

Ive thought about maybe creating a wrapper/tuple of span and object somewhere and unwrap it later... but I'm not sure it's possible

**Comment by safris** [comment]
As in my previous point: one plugin cannot depend on another. If your wrapper/tuple approach does not break this rule, then go for it. Otherwise, a different solution has to be invented. Is there a generic approach that can be used instead? The OpenTracing API has a mechanism of propagating context: parent spans. Are the reactive streams properly propagating spans?

**Comment by jam01** [comment]
As I mentioned, the reactor streams setup can't be supported because it's not one continuous stream. I may have misspoken when I talked about multiple Rules. Basically from one single Plugin I need two rules, or perhaps I should say I need two different class transformations, to interact with a single Map[object, span].

**Comment by safris** [comment]
Oh, if it's in the same "plugin", then you can just create a map that is locally accessible to that plugin. I think there is one or a couple plugins that have something like this. I guess the bottom line in this setup is to make sure that the state you'll be sharing between the two rules (in the same plugin) is "generally correct regarding the logical relation between the two rules".

**Comment by jam01** [comment]
I went ahead and created a singleton map, basically borrowed, from the java-agent and am successfully using that. Thanks, Seva.
