### ISSUE TITLE
Status of java-web-servlet-filter

### ISSUE THREAD

**Issue by moertel** [opentracing-contrib/java-specialagent#400]
I noticed that java-web-servlet-filter apparently isn't taken from its [repo](https://github.com/opentracing-contrib/java-web-servlet-filter) as-is but there's some code been copied over (?) to https://github.com/opentracing-contrib/java-specialagent/tree/master/rule/servlet/src/main/java/io/opentracing/contrib/web/servlet/filter

As there's been some bugfix activity today and a new version [0.4.1](https://github.com/opentracing-contrib/java-web-servlet-filter/releases/tag/0.4.1) has been released, how will this fix make it into the specialagent?

**Comment by safris** [comment]
Hi @moertel, thank you for notifying us about this bug fix. You are correct, SpecialAgent has a custom version of `java-web-servlet-filter`. This was necessary because `java-web-servlet-filter` only supports Servlet API 3+ (does not support Servlet API 2.3 or 2.5). I had wanted to submit a PR to supplement `java-web-servlet-filter` with the added support of Servlet API 2.3 and 2.5, but the code to achieve this in SpecialAgent has kind of been a mess, and I wouldn't want to bring that mess into `java-web-servlet-filter`.

As for [v0.4.1](https://github.com/opentracing-contrib/java-web-servlet-filter/releases/tag/0.4.1): I will merge this fix into SpecialAgent's `servlet` rule.

**Comment by safris** [comment]
Hi @moertel, this has been done.

**Comment by moertel** [comment]
Thanks a lot, @safris!
