### ISSUE TITLE
Support target runtimes that import OpenTracing API

### ISSUE THREAD

**Issue by william-tran** [opentracing-contrib/java-specialagent#440]
I'm trying to dynamic attach to a spring boot app that uses some manual OpenTracing instrumentation, but unless this is done very early on, I get `java.lang.IncompatibleClassChangeError` or `java.lang.LinkageError`. Is this a known issue or by design? 

e.g. 
`
java.lang.LinkageError: loader constraint violation: when resolving method "io.opentracing.tag.BooleanTag.set(Lio/opentracing/Span;Ljava/lang/Boolean;)V" the class loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) of the current class, com/acme/MyClass, and the class loader 'bootstrap' for the method's defining class, io/opentracing/tag/BooleanTag, have different Class objects for the type io/opentracing/Span used in the signature
`

**Comment by safris** [comment]
Hi @william-tran, are you trying to do a dynamic attach to a runtime that imports the OpenTracing API?

**Comment by william-tran** [comment]
@safris yes; OpenTracing 0.33.0 is on the `<compile>` classpath

**Comment by safris** [comment]
Hi @william-tran, the reason you're receiving a `LinkageError` is because SpecialAgent provides the OpenTracing API by itself. Your use-case is outside of SpecialAgent's original scope -- i.e. a situation where you intend to automatically instrument a runtime that is already manually instrumented. Therefore, the only thing I can provide you with immediately is a workaround that will allow you to get past this issue: You need to ensure that the classes for the OpenTracing API are not present in the application's classpath.

**Comment by william-tran** [comment]
Ok thanks for confirming this; its unfortunate as I was looking for a programmatic and portable way to ensure agent attachment at runtime and test. Mixing manual and auto-instrumentation is something that's necessary in many cases I've found.  I put together a test app to try the various cases: https://github.com/william-tran/specialagent-spring-boot. It's not a total dealbreaker though;  I can resort to using the -javaagent flag.

**Comment by safris** [comment]
Hi @william-tran, thank you for this test app. I've know about this deficiency in SpecialAgent for some time, but we have never had a direct use-case that required it to be fixed. Your use-case has this requirement, and so I will prioritize the work to resolve this issue for milestone [v1.6.0](https://github.com/opentracing-contrib/java-specialagent/milestone/7).

**Comment by safris** [comment]
Hi @william-tran, I am having trouble reproducing this bug with the test app you provided. I keep getting this in the logs:

```
--- [           main] c.e.s.SpecialagentDemoApplication        : external attach process failed, exit status 1
```

Additionally, I have to say that your use-case is very unusual. Here are my "level 1" set of comments, as to why your use-case is unusual:
1. You package SpecialAgent into the application JAR. This is not how SpecialAgent is intended to be used. SpecialAgent is not intended to be packaged anywhere -- it is meant to be executed in standalone fashion from the CLI.
1. You import `net.bytebuddy.agent` libs in your application. This is dangerous, because SpecialAgent imports these same libs into the bootstrap class loader. Even if we get the OT API issues fixed, then we'd have the same issues to fix with ByteBuddy, but we'd be out of luck because ByteBuddy is outside of SpecialAgent.

I understand that you want to include your own OT instrumentations in your app, and also use SpecialAgent. This is a valid use-case. This effectively means that you need to have the OT APIs available to your application, which is reasonable.

If you switch from dynamic attach to static attach, then all of your issues will disappear. Here is why:

With your current approach using dynamic attach, here is what's happening:
1. Your application loads all of the OT APIs into the system class loader.
1. You attach SpecialAgent to your process, which loads the OT APIs into the bootstrap class loader. Now there are versions of the OT APIs in your runtime: in the system class loader, and in the bootstrap class loader.
1. You run your application, and get a `LinkageError` because the classes from the 2 versions of OT APIs cross.

Now let's explore the static attach approach:
1. You start your app with `-javaagent:SpecialAgent.jar`.
1. The SpecialAgent runtime loads the OT APIs into the bootstrap class loader.
1. Your application loads after SpecialAgent loads. When the `ClassLoader.loadClass` method is called for each OT API class, it is resolved against the classes loaded in the bootstrap class loader.
1. Your application does not load a 2nd version of the OT APIs, and everything works as expected.

I am reluctant to implement any changes to the SpecialAgent in order to support your dynamic approach. The reason is due to the fact that such a solution would end up being extraneously complex. SpecialAgent would have to have a bridge between different versions of the OT API loaded in different class loaders.

Would you mind trying the static attach approach?

**Comment by william-tran** [comment]
The demo app's pom.xml downloads the SA jar but doesn't package it into the application, the `copy-dependencies` invocation is there for convenience. The dependency on ByteBuddy is also there for convenience of dynamic attach, but could be avoided as well. 

Regardless, 

>The reason is due to the fact that such a solution would end up being extraneously complex. SpecialAgent would have to have a bridge between different versions of the OT API loaded in different class loaders.

That's totally fine. The use case I was hoping to support was around test-driven development and being able to programmatically attach the agent in JUnit tests, without having to rely on external config like surefire/failsafe or your IDE. I ended up doing that (-javaagent in failsafe args) anyways and it does work.

**Comment by safris** [comment]
Great, I'm happy you found a workaround that is suitable!
