### ISSUE TITLE
Rewritable Tracer not relatable to Integrations

### ISSUE THREAD

**Issue by jianshaow** [opentracing-contrib/java-specialagent#493]
I don't know if "Rewritable Tracer" the feature is supported formally or not in v1.6.0, but I added the `-Dsa.rewrite=xxx` jvm option to my demo application and request a servlet, `NullPointerException` was thrown just like below
~~~
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.opentracing.contrib.specialagent.RewritableTracer.getRulesForCurrentPlugin(RewritableTracer.java:42)
	at io.opentracing.contrib.specialagent.RewritableTracer.buildSpan(RewritableTracer.java:98)
	at io.opentracing.util.GlobalTracer.buildSpan(GlobalTracer.java:194)
	at io.opentracing.contrib.specialagent.rule.servlet.ext.TracingFilterUtil.buildSpan(TracingFilterUtil.java:36)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:183)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
~~~
I checked the code, I guest, `AgentRule.getCurrentPluginName()` return null in the invocation context (RewritableTracer.java:42). Some plugin intercept the traffic and build spans, just like redis. But most of rule interceptions are just for integrating a 3rd-party instrument, not handling traffic tracing. in that cases, buildSpan is invoked in another thread by the 3rd-party libraries, not by rule interceptions, current plugin name could not be found by `AgentRule.getCurrentPluginName()`.

**Comment by safris** [comment]
Hi @jianshaow, you bring up a very valid use-case. I will look at this and will figure out a fix.

**Comment by safris** [comment]
Hi @jianshaow, so this issue is a bit challenging to figure out. Basically, the Rewritable Tracer architecture associates rules to be specific to certain plugins. However, your use-case shows that it may not be possible to know which plugin is resulting in the OT API calls. The only "correct thing" I can figure out in this case is to just have the Rewritable Tracer apply the global rules (i.e. the ones that have a rule name of "*"). @zeitlinger, what are your thoughts?

**Comment by zeitlinger** [comment]
@safris I've looked at the instantiation part of rewritable tracer before and didn't get the logic.

So let me explain what my initial idea was - hoping that this will lead somewhere:

1. A new instance of Rewritable Tracer is created for each plugin during the bootstrap phase of specialagent
2. This instance is passed to the plugin

In this setup, there would be no need to figure out the current plugin anywhere.

**Comment by jianshaow** [comment]
@safris @zeitlinger , this is a really useful feature for me, even if no plugin grain support it can be a acceptable solution for me.

**Comment by safris** [comment]
@zeitlinger, the architecture you describe is conceptually correct. The challenge here is that a `Tracer` is not "passed to a rule/plugin", because that's not how the OT API operates. Unfortunately, the mechanism by which a `Tracer` is provided by OT API is via the `GlobalTracer`, whereby each rule or plugin just "grabs" the current `Tracer` instance by calling `GlobalTracer.get()`.

It would definitely be better if we "provided a specific `Tracer` instance to each rule/plugin", but this is not how rules and plugins are already implemented. For such a refactor, we'd have to modify all the Instrumentation Plugins in [opentracing-contrib](https://github.com/opentracing-contrib/).

Therefore, to conform to the OT API's `GlobalTracer`, there can only be one `Tracer` instance. And so, this instance has to determine which rule/plugin is executing the OT API to correlate to the correct rewrite rules.

@jianshaow, if my [last edit](https://github.com/opentracing-contrib/java-specialagent/commit/aa71d2b1cc0e845f301bca9cdc671c654fda94be) works for you now, then let's keep that tweak for now, and we can keep this issue open until we figure out a better approach.

**Comment by zeitlinger** [comment]
> whereby each rule or plugin just "grabs" the current `Tracer` instance by calling `GlobalTracer.get()`.

The idea was not to use GlobalTracer at all. This would mean changing all rules, but we control the source code, so this should be possible.

**Comment by jianshaow** [comment]
@safris , I tested it, no more NPE. it works well as a global span rule engine.

**Comment by safris** [comment]
For the rules, yes you are correct @zeitlinger. But this is not so for the plugins (for example: [java-jdbc](https://github.com/opentracing-contrib/java-jdbc/blob/e99aad80b5322767e57ed340dbf169cba70a8efe/src/main/java/io/opentracing/contrib/jdbc/TracingDriver.java#L284)).

**Comment by zeitlinger** [comment]
@safris for java-jdbc, we could add a static `setTracer` method. WDYT?

**Comment by safris** [comment]
@zeitlinger, the `java-jdbc` example I showed you is just one of many external plugins. It is unreasonable to require each plugin owner to update his code simply for Rewritable Tracer. As far as the OT API, they are doing everything correctly. Even if we did get everyone to update their plugins, then we'd effectively be hacking around a limitation in the OT API -- something that is only a limitation for Rewritable Tracer, and nobody else. And even if we did go this way, then we'd effectively be saying: "the OT API is flawed, and we've required all Instrumentation Plugins to use an alternate method by which `Tracer` instances are obtained". This is a stack of arguments that lead me to believe that Rewritable Tracer itself needs to be amended in some way to cooperate with the OT API, rather than hack around it.

**Comment by zeitlinger** [comment]
> @zeitlinger, the `java-jdbc` example I showed you is just one of many external plugins. It is unreasonable to require each plugin owner to update his code simply for Rewritable Tracer. 

that's a fair point - maybe there's another way - such as detecting where the call to `GlobalTracer.get()` is coming from.

In the case of `java-jdbc`, we could set the private tracer field using reflection - but this only works in plugins that have such a caching mechanism.

> As far as the OT API, they are doing everything correctly....

looking forward, open telemetry does address this problem - you are basically saying: give me a tracer for library x, version y. It will be a while, however, until this migration is over.

**Comment by safris** [comment]
The main reason we are having this problem here is because OpenTracing API does not have a concept of a "plugin". The idea of a "plugin" is on a level above the OT API, so we're trying to figure out a way to identify a "plugin" within the constraints of the OT API. Unfortunately, this is not possible with the `GlobalTracer` approach. Event when "detecting where the call to GlobalTracer.get() is coming from", there is no way to figure out the name of a "plugin", because there is no such concept in OT API. Plugin names were invented by SpecialAgent.

**Comment by safris** [comment]
@zeitlinger, I had more thoughts about this issue: "there is no concept of a 'plugin' in OpenTracing -- i.e. there is no bundling of code and labeling of this bundle with some name". The same goes for OpenTelemetry. If you think about it, your configuration architecture for Rewritable Tracer allows for rules to be associated with plugins (named plugins). For a rule to be active, it first has to match the name. So, in effect, it's like a pre-matching condition. For SpecialAgent, this works fine because SpecialAgent names its rules and plugins. But for applications that also incorporate their own instrumentations, this will not work, because those instrumentations are not in a bundle and do not have a name. Therefore, I feel there is an argument to remove this complexity from the Rewritable Tracer altogether. As in, all rules would become global. I don't see any other clean way around this. Furthermore, it would be impossible for the API to define such a bundling and naming spec, because custom instrumentation that is integrated directly into application code is not bundleable, and thus not nameable.

**Comment by zeitlinger** [comment]
> @zeitlinger, I had more thoughts about this issue: "there is no concept of a 'plugin' in OpenTracing -- i.e. there is no bundling of code and labeling of this bundle with some name". The same goes for OpenTelemetry. 

OpenTelemetry is addressing this issue with [TracerProvider](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/TracerProvider.java#L41). It's called `instrumentation` instead of `plugin`, but the concept is the same.

> Therefore, I feel there is an argument to remove this complexity from the Rewritable Tracer altogether. As in, all rules would become global. 

To me, this feels like sacrificing essential functionality without providing an alternative - not the best solution for our users.

I would like to take the opposite direction: Looking into the future, open telemetry "instrumentation" is the right API that supports our use case. Let's try to make this idea a reality in the old open tracing world where possible.

**Comment by safris** [comment]
@zeitlinger, even with OpenTelemetry's `TracerProvider`, the use of a valid name is not compulsory:

> In case an invalid name (null or empty string) is specified, a working default Tracer implementation as a fallback is returned rather than returning null or throwing an exception. A library, implementing the OpenTelemetry API may also ignore this name and return a default instance for all calls, if it does not support "named" functionality (e.g. an implementation which is not even observability-related).

Since the name is not compulsory, Rewritable Tracer would have to support the default behavior, which would mean that only the global rules would apply.

So the follow-up question is: what is the underlying reason we're trying to have Rewritable Tracer support declaration of rules that are "integration specific" (rather than just have global rules).

**Comment by zeitlinger** [comment]
> So the follow-up question is: what is the underlying reason we're trying to have Rewritable Tracer support declaration of rules that are "integration specific" (rather than just have global rules).

This originates in my original use case: `db.statement` in `jedis` is problematic, but `db.statement` in `jdbc` is fine.

What is problematic? 
jedis does not use placeholders ("?") for query parameters and the arguments are sensitive data (in my case) that must not be put in spans.

What would the rewrite rule be?
Drop all `db.statement` tags for `jedis`

What would be an alternative?
Create a conditional rewrite rule for each possible jedis statement, e.g. `select \* from user.*` - assuming that there is no overlap with `jdbc` db statements.

**Comment by safris** [comment]
What about a conditional regex to match `^select [^?]+$`, or something of this nature? I do see that your use-case would be much easier handled if we had named integrations. Right now, Rewritable Tracer uses a hacked together concept of named integrations for OpenTracing that is based on "what is the currently executing integration" variable that is set as a static field in the `AgentRule` class. The limitation of this, as this issue brought to our attention, is that if the integration is not executed via `AgentRule`, then the name will be null. As in @jianshaow's use-case, to work around this limitation, he has to create global rules. If you think about it, people will end up always writing global rules, because there is simply no way to easily know if Rewritable Tracer will encounter a null name or not. If we try to fit Rewritable Tracer in OpenTelemetry, we will also have the situation where the name may be null. Instead of relying on named integrations as a rule pre-matching, perhaps there is another way to strengthen the selectability of spans to rewrite based on other information available in the span/span builder/tracer.

**Comment by zeitlinger** [comment]
Hi @safris - I'm getting the impression that we've covered all the different alternatives by now and it's up to you (as the maintainer) to make a call.

There's one thing that I've learned recently - not sure if it's also new to you:
[java-api-extensions](https://github.com/opentracing-contrib/java-api-extensions) (and it's [Zalando flavor](https://github.com/zalando/opentracing-toolbox/tree/master/opentracing-proxy)) have a similar focus as RewritableTracer.

Now answering your last comment:

> What about a conditional regex to match `^select [^?]+$`, or something of this nature? 

Yes, that would be possible for some uses cases - see [comment above](https://github.com/opentracing-contrib/java-specialagent/issues/493#issuecomment-606461083)

> ... named integrations ...

I think we've covered the options here, both have their pros and cons:
1. [more support](https://github.com/opentracing-contrib/java-specialagent/issues/493#issuecomment-604412889) - which I've argued for
2. Complete removal - which you've argued for
3. Current limited support - might be a compromise - but hard to understand

Once we're talking about open telemetry, another option might make more sense.

**Comment by zeitlinger** [comment]
Just found out that the OpenTelemetry equivalent to this project is using the named instrumentation pattern, e.g. [akka](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/instrumentation/akka-http-10.0/src/main/java/io/opentelemetry/auto/instrumentation/akkahttp/AkkaHttpClientDecorator.java#L30), [jdbc](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/instrumentation/jdbc/src/main/java/io/opentelemetry/auto/instrumentation/jdbc/DataSourceDecorator.java#L26).

**Comment by safris** [comment]
Hi @zeitlinger, thank you for the assessment of the options. I think the best option for us here is (3). This choice retains the work that's been done, and leaves a possibility for further improvements based on realizations we may not have yet. So, in short, I'm going to keep the implementation of Rewritable Tracer as is. Furthermore, I have written up a draft proposal for the port of this implementation to the [OTel Auto Instr engine](https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/309).

**Comment by safris** [comment]
Closing this, as there is nothing actionable remaining with this issue.
