### ISSUE TITLE
Opentracing API v0.33?

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#563]
Is there a reason that v0.33 of the Java OpenTracing API hasn't been used here? I know with the move to OpenTelemetry that this might be a moot point. But I was looking to upgrade my fork due to Wavefront Opentracing SDK's new versions requiring it. I wanted to ask if there are any gotchas (other than some of the tests needing rework that I noticed)...

**Comment by safris** [comment]
Hi @randallt, the SpecialAgent deliberately stayed on OT API v0.32, and the reason is due to the nature of changes from OT API v0.32 to v0.33. If you inspect the differences, you'll see that OT API v0.33 simply has removed the methods marked as deprecated, making v0.33 a direct subset of v0.32. Therefore, Integration Rules and applications that are bound to OT API v0.33 will also plug directly into v0.32. Leaving SpecialAgent on v0.32 allows it to support both v0.32 and v0.33.

**Comment by randallt** [comment]
But if I want to use a tracer that only supports v0.33, it's not going to work, right?

**Comment by safris** [comment]
It will work, because the deprecated methods have implementations that bridge to non-deprecated methods.
